name: recycle_go
description: "Mobile application assignment RSW Y2S3 G10"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  image: ^4.8.0
  intl: ^0.20.2
  provider: ^6.1.2
  supabase_flutter: ^2.12.4
  camera: ^0.11.2
  flutter_vision: ^2.0.0
  image_picker: ^1.0.7
  crypto: ^3.0.3
  permission_handler: ^11.3.1
  path_provider: ^2.1.2
  cupertino_icons: ^1.0.8
  salomon_bottom_bar: ^3.3.2
  tflite_flutter: ^0.12.1
  google_maps_flutter: ^2.6.0
  mobile_scanner: ^3.5.5
  geolocator: ^11.0.0
  email_otp: ^3.1.0
  email_auth: ^2.0.0
  qr_flutter: ^4.1.0
  share_plus: ^7.2.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.1
  pdf: ^3.10.0
  printing: ^5.11.0
  app_links: ^6.3.2
  mailer: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/models/model.tflite
    - assets/images/background_image/
    - assets/models/best_model.tflite
    - assets/models/labels.txt

l10n:
  arb-dir: lib/l10n        # or your custom path
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
