name: recycle_go
description: "Mobile application assignment RSW Y2S3 G10"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  camera: ^0.12.0+1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  image: ^4.8.0
  intl: ^0.20.2
  provider: ^6.1.2
  supabase_flutter: ^2.12.0
  tflite_flutter: ^0.12.1
  google_maps_flutter: ^2.6.0
  mobile_scanner: ^5.1.1
  geolocator: ^11.0.0
  salomon_bottom_bar: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/models/best_model.tflite
    - assets/models/labels.txt

l10n:
  arb-dir: lib/l10n        # or your custom path
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart